name: PHP Composer

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log php version
      run: php -v

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run codestyle check
      run: ./vendor/bin/ecs --config=dev/ecs/ecs.php

    - name: Run unit test suite
      run: ./vendor/bin/phpunit -d memory_limit=1G tests

    - name: Run static analysis
      run: ./vendor/bin/phpstan analyse --configuration dev/phpstan/phpstan.neon
